spring:
  application:
    name: export
  datasource:
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    url: ${DATABASE_HOST_JDBC:jdbc:postgresql://localhost:5432}/export
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/master.xml
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: ${SERVER_HTTP_PORT:8085}
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
s3:
  endpoint: ${S3_HOST:https://test.ru}
  access-key: ${S3_ID:ID}
  secret-key: ${S3_KEY:KEY}
  region: ${S3_REGION:ru-central-1}
  bucket: ${S3_BUCKET:hack-2024}